### ISSUE TITLE
Some video are loading really slow

### ISSUE THREAD

**Issue by IceBeach7** [mauriceoegerli/viewtube-vue#2217]
### Describe the Bug
Some videos are stuck on the loading screen, some buffer every few seconds. If you try to watch the same video about 2 hours later, it will most likely work.

### Steps to Reproduce the Bug
1. Click on some video, where this happens
2. Wait some time
3. It will most likely work

**Comment by moisout** [comment]
Thank you for creating this issue. I have since switched the proxy for video playback. You might need to wait a moment in order for a video to start, but once it's playing it should buffer nicely. 
One thing to note is, the ViewTube server is located in Germany, so if you are far away from there the performance will be worse.
